### ISSUE TITLE
Community Exchange Introduction/Tracking:

### ISSUE THREAD

**Issue by ericdrosado** [rawheel/MyUnfollowers-App#4]
👋 Hi @rawheel ,

I am your GitHub mentor for the GitHub Education, [Community Exchange](https://airtable.com/shrRJ3AvEZQohOdGV) (CX) project. I'll be collaborating with you on preparing your repo for CX. 

You mentioned in your submission that you wanted to submit a `Learn + Collaborate` repo. This means that you would like to teach students, step by step, how to build this project as well as invite other students to collaborate and add features to this repo. I will generate issues, which will provide guidance on how to prepare your repo for a `Learn + Collaborate` CX submission on June 1, 2022.

This issue will serve as a tracking issue to track all issues related to CX. I recommend creating a new branch for every issue and opening a pull request to track changes so we can effectively collaborate with each other and merge changes when you and I feel like those changes are ready to be merged on your primary branch. 

If you have any questions or concerns, please feel free to leave a comment on this issue or any of the other issues that are generated. 

I look forward to working with you :octocat: 

## CX Issues
- [ ] https://github.com/rawheel/MyUnfollowers-App/issues/5
- [x] https://github.com/rawheel/MyUnfollowers-App/issues/6
- [x] https://github.com/rawheel/MyUnfollowers-App/issues/7
- [x] https://github.com/rawheel/MyUnfollowers-App/issues/8
- [x] https://github.com/rawheel/MyUnfollowers-App/issues/9
- [x] https://github.com/rawheel/MyUnfollowers-App/issues/10
- [x] https://github.com/rawheel/MyUnfollowers-App/issues/11

**Comment by rawheel** [comment]
Hey @ericdrosado, Hoping you're doing great.

I just got free from my midterms and sure I will consider these CX Issues and act accordingly. Excited and looking forward to working with you too. :)

**Comment by ericdrosado** [comment]
I hope midterms went well @rawheel . Let me know if there is anything I can help with.

**Comment by rawheel** [comment]
Hey @ericdrosado, midterms went great thanks for asking, I've been busy with other deadlines related to my final year project. 
I've worked on a few issues you can check them and let me know if there are any suggestions. I'll be working on the left ones and can you guide me is there any form I'll have to fill to submit this repo on 1st June?

**Comment by ericdrosado** [comment]
On June 1st I'll send a link to CX beta where you can upload your repo. 

Please make sure your repo issues are completed before then.

**Comment by rawheel** [comment]
sure, I've my project presentations today at university. will be working on it once I get back home.

**Comment by ericdrosado** [comment]
@rawheel I'll be delaying the invitation to later today or Friday at the latest. I just wanted to let you know. 

I hope your presentations went well!

**Comment by rawheel** [comment]
@ericdrosado Ahh thanks very much man, I'm working on it and will update you very soon.

**Comment by ericdrosado** [comment]
@rawheel you are welcome to change your submission type to a `Collaborate` repo versus a `Collaborate + Learn` repo if it makes submission easier for you given your busy schedule. 

I am going to send you the invitation since you have met all the requirements for a `Collaborate` repo.

**Comment by rawheel** [comment]
@ericdrosado Sure, Thanks.
